package com.example.pantryhub_assignment3_fy.model

enum class ActivityActionType {
    INVENTORY_ITEM_CREATED,
    INVENTORY_ITEM_UPDATED,
    STOCK_REDUCED,
    WASTE_RECORDED,
    RESTOCK_ORDER_CREATED,
    RESTOCK_ORDER_ORDERED,
    RESTOCK_ORDER_IN_TRANSIT,
    RESTOCK_ORDER_RECEIVED,
    RESTOCK_ORDER_CANCELLED,
    INVENTORY_ITEM_DELETED,
    SUPPLIER_CREATED,
    SUPPLIER_UPDATED,
    SUPPLIER_DELETED,
    STOCK_MOVEMENT_RECORDED,
    BRANCH_TRANSFER_RECORDED
}
