package com.example.pantryhub_assignment3_fy.model

data class InventoryItem(
    val id: String = "",
    val sku: String = "",
    val barcode: String = "",
    val name: String = "",
    val brand: String = "",
    val category: String = "",
    val branchId: String = "",
    val branchName: String = "",
    val storageLocation: String = "",
    val quantity: Double = 0.0,
    val unit: String = "",
    val costPrice: Double = 0.0,
    val sellingPrice: Double = 0.0,
    val minimumStockLevel: Int = 0,
    val reorderPoint: Int = 0,
    val maximumStockLevel: Int = 0,
    val reorderThreshold: Double = 0.0,
    val aisle: String = "",
    val shelf: String = "",
    val addedDate: Long = 0L,
    val expiryDate: Long = 0L,
    val batchNumber: String = "",
    val shelfLifeDays: Int = 0,
    val reminderDaysBefore: Int = 0,
    val notes: String = "",
    val supplierId: String = "",
    val supplierName: String = "",
    val supplierPhone: String = "",
    val supplierEmail: String = "",
    val imageUrl: String = "",
    val tags: List<String> = emptyList(),
    val status: String = InventoryStatus.FRESH.name,
    val createdBy: String = "",
    val updatedBy: String = "",
    val createdAt: Long = 0L,
    val updatedAt: Long = 0L,
    val isArchived: Boolean = false,
    val archivedAt: Long = 0L,
    val archivedBy: String = "",
    val archiveReason: String = "",
    val expiryLotsInitialized: Boolean = false,
    val expiryLots: List<ExpiryLot> = emptyList()
)
